name: Build next js project

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

# Optional
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT REPO
        uses: actions/checkout@v4
      - name: SETUP NODE
        uses: actions/checkout@v4
        with:
          node-version: '20'

      - name: setup pages
        uses: actions/configurre-pages@v5
        with:
          static_site_generator: next

      - name: INSTALL DEPEDENCIES
        run: npm INSTALL

      - name: BUILD NEXT JS PROJECT
        run: npm run build

      - name: upload artifact
        uses: action/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: DEPLOY GITHUB pages
        uses: action/deploy-pages@v3